name: CI

on: [ push ]

jobs:
  first:
    concurrency:
      group: single-group

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log hello
        run: echo "Hello at first time"

  second:
    concurrency:
      group: single-group

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log hello
        run: echo "Hello at the second time"

  third:
    concurrency:
      group: single-group

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log hello
        run: echo "Hello at the third time"

  fourth:
    concurrency:
      group: single-group

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log hello
        run: echo "Hello at the fourth time"
