name: Log the input

on:
  workflow_call:
    inputs:
       something:
        default: workflow_CALL_input_default_value
        type: string
        required: false

  workflow_dispatch:
    inputs:
      something:
        type: choice
        description: Choose something
        required: true
        default: workflow_dispatch_input_default_value
        options:
          - workflow_dispatch_input_primary_value
          - workflow_dispatch_input_secondary_value

jobs:
  deploy-rinkeby:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.something }}
      - run: echo ${{ github.event.inputs.something }}
