name: Reusable Workflow №2

on:
  workflow_call:
    inputs:
      something:
        default: workflow_CALL_input_default_value_of_the_second
        type: string
        required: false

concurrency:
  group: group_1
  cancel-in-progress: false

jobs:
  haha-job:
    runs-on: ubuntu-latest
    steps:
      - id: repository_owner
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}
      - id: step2
        run: echo ${{ steps.repository_owner.outputs.lowercase }}
