name: Deploy to the sandbox on PR into main branch

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run_first:
    uses: ElvisKrop/github-actions/.github/workflows/reusable-first.yml@develop

  run_second:
    uses: ElvisKrop/github-actions/.github/workflows/reusable-second.yml@develop
